import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { sanityClient, urlFor } from 'next-sanity'
import uuid from 'react-uuid'
import Image from 'next/image'
// const sanityClient = require('@sanity/client')

const recipesQuery = `*[_type == "recipe" ] {
  _id,
  name,
  slug,
  mainImage
}
`

export default function Home({ recipes }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Kodamas Smoothies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Kodamas Smoothies</h1>
      <ul>
        {recipes?.length > 0 && recipes.map((recipe) => (
        <li key={uuid()}>   
          <Link href="/">
            <a>
              <Image src={urlFor(recipe.mainImage).url()} alt="Smoothie" />
              <span>{recipe.name}</span>
            </a>
          </Link>
        </li>
        ))}
      </ul>
    </div>
  )
}

export async function getStaticProps() {
  const recipes = await sanityClient.fetch(recipesQuery)

  return { props: { recipes } };
}