import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { SanityClient, urlFor } from 'next-sanity'

export default function Home() {


  return (
    <div className={styles.container}>
      <Head>
        <title>Intro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </div>
  )
}

export function getStaticProps() {
  return {
    props: {
      data: {
        recipes: [{ title: 'Pineapple Smoothie'}]
      }
    }
  }

}